### ISSUE TITLE
Request for data split and Compcar, shapenet preprocessing code

### ISSUE THREAD

**Issue by mush881212** [nihalsid/stylegan2-ada-3d-texture#2]
Hi,

Could you release the data split (train, val, and test) with original Compcar IDs (e.g., 0a0da4a8fd29e8, 0a01c7b6ab4f68, ...), and the preprocessing  code of Compcar images and Shapenet car models?
Thanks!

**Comment by nihalsid** [comment]
Hi,

Thanks for the issue! Please check the config/ directory for the test splits (train split = all files - test). Will add instructions for preprocesing soon.

**Comment by nihalsid** [comment]
Hi, 

I've also added a walkthrough on how to preprocess data with an example: https://github.com/nihalsid/CADTextures

**Comment by ck-amrahd** [comment]
Hi,
I have downloaded the dataset from your Dropbox link. I cannot run the code because of dependency issues. I would like to compare our solution on the test dataset. I could not find out which meshes are in the test set. Also, for computing fid, the real_folder has all the exemplars images, am I right? And for creating the fake_dir, did you render a single image per test mesh from a fixed viewpoint? Thank you.
